### ISSUE TITLE
problem with de plugin no working

### ISSUE THREAD

**Issue by matbott** [MegaphoneJon/redmine_email_attachments#1]
Hello, I installed the plugin but it does not send the attachments by mial, I check the code and change the file path from image_path = '/usr/src/redmine/files/' to image_path = '/root/redmine/files/' which it's where my files are saved
Run the command RAILS_ENV=production bundle exec rake redmine:plugins:migrate NAME=redmine_email_attachments
I restarted httpd service but it doesn't work for me.
Is there something else to modify or try, I am very interested in this plugin

**Comment by fonya** [comment]
Try to set "language = auto", for the users.

**Comment by MegaphoneJon** [comment]
Thanks @fonya.  I'm not a Ruby programmer so I can't really give support to this.  I honestly don't even remember how I managed to cobble this together.  I wish I could help more @matbott - but you can see that I have 270 Github repos, and only this one is Ruby.
